name: tfm_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=1.5.3
  - numpy=1.23.5
  - seaborn=0.11.2
  - scikit-learn=1.0.2
  - matplotlib=3.4.3
  - geopandas=0.12.2
  - fiona=1.8.21
  - shapely=1.8.1
  - pip
  - pip:
      - matplotlib==3.4.3